version: '3.7'

services:
 streamlit_skills:
    build: .
    image: streamlit:0.0.1
    volumes:
      - ./app:/usr/src/app
      - ./config.ini:/usr/src/app/config.ini
    environment:
      - PORT=5000
    ports:
      - "5001:5000"
    container_name: streamlit_skills
    restart: unless-stopped
